CREATE TABLE users(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at DATE DEFAULT (CURRENT_DATE),
    updated_at DATE,
    salt VARCHAR(16) NOT NULL
);

